name: Build GUI for Linux

on:
  push:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'
    - 'tsMuxer/**'
    - 'libmediation/**'
    - 'CMakeLists.txt'
  pull_request:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'
    - 'tsMuxer/**'
    - 'libmediation/**'
    - 'CMakeLists.txt'

jobs:
  build-linux-gui:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfreetype-dev zlib1g-dev
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.*'
        modules: 'qtmultimedia'
      
    - run: ./.github/workflows/linux_gui.sh
      name: build-linux-gui
