name: Build GUI for Linux

on:
  push:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'
  pull_request:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'

jobs:
  build-linux-gui:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.*'
        modules: 'qtmultimedia'
      
    - run: ./.github/workflows/linux_gui.sh
      name: build-linux-gui
