name: Build for Mac

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-mac-native:

    runs-on: macos-15
    strategy:
      matrix:
        include:
          - arch: arm64
          - arch: x86_64
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.*'
        modules: 'qtmultimedia'
      
    - run: ./scripts/build_macos_native.sh
      name: build-for-mac
      env:
        CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}

    - name: Rename zip with architecture
      run: mv build/bin/mac.zip build/bin/mac-${{ matrix.arch }}.zip

    - uses: actions/upload-artifact@v4
      with:
         name: tsMuxer-${{ matrix.arch }}
         path: build/bin/mac-${{ matrix.arch }}.zip
      name: upload-artefact
