name: Build for Mac Native

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-mac-native:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.*'
        modules: 'qtmultimedia'
      
    - run: ./scripts/build_macos_native.sh
      name: build-for-mac

    - uses: actions/upload-artifact@v4
      with:
         name: tsMuxer
         path: build/bin/mac.zip
      name: upload-artefact
