name: Nightly Releases

on:
  schedule:
    - cron:  '1 1 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ steps.check.outputs.status }}
      version: ${{ steps.check.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      with:
        fetch-depth: 0
    
    - name: nightly-check
      id: check
      shell: bash {0}
      run: |
        ver=$(./.github/workflows/nightly_check.sh)
        echo "status=$?" >> $GITHUB_OUTPUT
        echo "version=${ver}" >> $GITHUB_OUTPUT

    - name: create-release
      id: create
      if: steps.check.outputs.status == 0
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly-${{ steps.check.outputs.version }}
        name: Nightly build from ${{ steps.check.outputs.version }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-docker:
  
    needs: check

    if: needs.check.outputs.status == 0
  
    runs-on: ubuntu-latest
    
    container:
      image: docker://jaminmc/tsmuxer_build:latest
      volumes:
      - /workspace:/github/workspace
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      
    - run: rm -f bin/.gitkeep
      name: clean-bin-folder
      
    - run: ./scripts/rebuild_linux_with_gui_docker.sh
      name: build-for-linux
      
    - run: ./scripts/rebuild_mxe_with_gui_docker.sh
      name: build-for-win64
      
    - run: ./scripts/rebuild_mxe32_with_gui_docker.sh
      name: build-for-win32

    - run: ./scripts/rebuild_osxcross_docker.sh
      name: build-for-mac

    - name: Upload All Builds
      id: upload-builds
      uses: softprops/action-gh-release@v2
      with:
        files: ./bin/*.zip
        tag_name: nightly-${{ needs.check.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
