name: Nightly Releases

on:
  schedule:
    - cron:  '1 1 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ steps.check.outputs.status }}
      version: ${{ steps.check.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      with:
        fetch-depth: 0
    
    - name: nightly-check
      id: check
      shell: bash {0}
      run: |
        ver=$(./.github/workflows/nightly_check.sh)
        echo "status=$?" >> $GITHUB_OUTPUT
        echo "version=${ver}" >> $GITHUB_OUTPUT

    - name: create-release
      id: create
      if: steps.check.outputs.status == 0
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly-${{ steps.check.outputs.version }}
        name: Nightly build from ${{ steps.check.outputs.version }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-docker:
  
    needs: check

    if: needs.check.outputs.status == 0
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force

    - name: Pull Docker image
      run: docker pull jaminmc/tsmuxer_build:latest
      
    - run: rm -f bin/.gitkeep
      name: clean-bin-folder
      
    - name: build-for-linux
      run: >
        docker run --rm
        -v ${{ github.workspace }}:/work -w /work
        jaminmc/tsmuxer_build:latest
        ./scripts/rebuild_linux_with_gui_docker.sh
      
    - name: build-for-win64
      run: >
        docker run --rm
        -v ${{ github.workspace }}:/work -w /work
        jaminmc/tsmuxer_build:latest
        ./scripts/rebuild_mxe_with_gui_docker.sh
      
    - name: build-for-win32
      run: >
        docker run --rm
        -v ${{ github.workspace }}:/work -w /work
        jaminmc/tsmuxer_build:latest
        ./scripts/rebuild_mxe32_with_gui_docker.sh

    - name: build-for-mac
      run: >
        docker run --rm
        -v ${{ github.workspace }}:/work -w /work
        jaminmc/tsmuxer_build:latest
        ./scripts/rebuild_osxcross_with_gui_docker.sh

    - name: Upload All Builds
      id: upload-builds
      uses: softprops/action-gh-release@v2
      with:
        files: ./bin/*.zip
        tag_name: nightly-${{ needs.check.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
