name: Qt6 test build

on:
  push:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'
  pull_request:
    branches: [master]
    paths:
    - 'tsMuxerGUI/**'

jobs:
  build-qt6-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.*'
        modules: 'qtmultimedia'
      
    - run: ./.github/workflows/qt6_test.sh
      name: build-qt6-linux
